{% set name = "EOmaps" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EOmaps-{{ version }}.tar.gz
  sha256: faac156519b07dbd2d4d2149bd476d316cf591f87277a18938d6b8804b125aca
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - matplotlib-base >=3.0
    - cartopy >=0.20.0
    - descartes
    - mapclassify
    - pyproj
    - pyepsg
    - geopandas
    - owslib
    - requests
    - xmltodict
    - cairosvg
    - datashader

test:
  imports:
    - eomaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelquast/EOmaps
  summary: A library to create interactive maps of geographical datasets.
  license: GPL-2.0-or-later
  license_file: LICENSE

  description: |
    EOmaps is a python library to simplify the creation of interactive maps.

    With a few lines of code you can add WebMap services, annotations, markers,
    scalebars, overlays etc. to the plot.

    Many pre-defined callback functions are available to execute tasks
    (add annotations/markers, swipe layers etc.), when you click on the map.
    (custom callbacks are also supported!) 

    Check the documentation for more details & examples!

  doc_url: https://eomaps.readthedocs.io/
  dev_url: https://github.com/raphaelquast/EOmaps


extra:
  recipe-maintainers:
    - raphaelquast
