{% set name = "eomaps" %}
{% set version = "8.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eomaps-{{ version }}.tar.gz
  sha256: a7018f55f77f4d3b70be28ba6139ec6877aed513d03aa595872d1d943f0afaf1
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eomaps = eomaps.scripts.open:cli

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib >=3.4
    - cartopy >=0.20.0
    - pyproj
    - packaging
    - click
    - pandas
    - geopandas
    - mapclassify
    - datashader
    - owslib
    - requests
    - qtpy

test:
  imports:
    - eomaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelquast/EOmaps
  summary: A python package to create interactive maps of geographical datasets.
  license: BSD-3-Clause
  license_file: LICENSE

  description: |
    EOmaps is a python package to visualize and analyze geographical datasets.

    It aims to provide a comprehensive, flexible, well-documented and easy-to-use API 
    to create publication-ready maps that can directly be used for interactive data analysis. 

    EOmaps is built on top of matplotlib and cartopy and integrates well with the scientific 
    python infrastructure (e.g., numpy, pandas, geopandas, xarray etc.), allowing you to 
    visualize point-, raster- or vector-datasets provided in almost any format you can imagine, 
    no matter if you're dealing with just a few unsorted datapoints or multi-dimensional stacks 
    of global high-resolution datasets.

    Figures created with EOmaps are multi-layered, so you can (transparently) overlay and 
    interactively compare your datasets with ease. With the accompanying GUI widget, you can 
    quickly switch layers, change the layout, examine the large collection of features and 
    web-map services, and explore the capabilities of EOmaps. Once you're map is ready, you 
    can export it as high-resolution image or vector-graphic for further editing. 
    Leveraging the powers of matplotlib, you can also embed interactive maps in 
    Jupyter Notebooks, on a webpage or in GUI frameworks like Qt, tkinter etc..
    
    Check the documentation for more details & examples!

  doc_url: https://eomaps.readthedocs.io/
  dev_url: https://github.com/raphaelquast/EOmaps


extra:
  recipe-maintainers:
    - raphaelquast
