{% set name = "EOmaps" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EOmaps-{{ version }}.tar.gz
  sha256: 4e58619e2395a2d77503b64cf00293ae6df0bc7cf513fc38974a4c364a4dc00f
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy <1.24 # check progress of https://github.com/numba/numba/pull/8691
    - scipy
    - pandas
    - matplotlib >=3.4
    - cartopy >=0.20.0
    - descartes
    - mapclassify
    - pyproj
    - pyepsg
    - geopandas
    - owslib
    - requests
    - xmltodict
    - cairosvg
    - datashader
    - packaging

test:
  imports:
    - eomaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raphaelquast/EOmaps
  summary: A library to create interactive maps of geographical datasets.
  license: GPL-2.0-or-later
  license_file: LICENSE

  description: |
    EOmaps is a python library to simplify the creation of interactive maps.

    With a few lines of code you can add WebMap services, annotations, markers,
    scalebars, overlays etc. to the plot.

    Many pre-defined callback functions are available to execute tasks
    (add annotations/markers, swipe layers etc.), when you click on the map.
    (custom callbacks are also supported!) 

    Check the documentation for more details & examples!

  doc_url: https://eomaps.readthedocs.io/
  dev_url: https://github.com/raphaelquast/EOmaps


extra:
  recipe-maintainers:
    - raphaelquast
